var party = [],
	adversary = [],
	selectedFighter,
	initiativePosition = 0,
	enemyHealth,
	maleNameArray = ["Billy", "Jimmy", "Teddy", "Fred"],
	femaleNameArray = ["Nancy","Jill", "Mary"],
	classArray = ["Monk", "Mage", "Warrior", "Ranger"],
	initiative = [],
	god = new Character("Artomous", "druid", 1, 10, 10);